name: Build and Publish Consumer
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: consumer
          wrapper-directory: consumer
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      
      - name: Upload consumer jar
        uses: actions/upload-artifact@v2
        with:
          name: consumer-jar
          path: consumer/build/libs/consumer-1.0.0.jar
  
  push_to_registry:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download consumer jar
        uses: actions/download-artifact@v2
        with:
          path: consumer/build/libs
          name: consumer-jar  

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: robsonbittencourt/kafka-example-consumer:latest
          context: consumer